### PR TITLE
Remove future-annotations as dependency and update minimum Python version

### LINKED ISSUE #11: Incorrect dependency in v0.15.0
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The conda-forge package still includes `future-annotations` as a dependency of this package.  However, it has been dropped as a dependency from the [Github repo](https://github.com/geopython/pygeoapi/blob/0.15.0/requirements.txt) as of v0.15.0.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

### PR DESCRIPTION
**Pull request by DManowitz**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Fixes #11

### CODE REVIEW

**Comment by DManowitz** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
We probably need to pin pydantic to <2

**Comment by ocefpaf** [comment]
@DManowitz, last but not least, do you want to add yourself as a maintainer here?

**Comment by DManowitz** [comment]
> @DManowitz, last but not least, do you want to add yourself as a maintainer here?

Sure, but can you tell me what I need to do?

**Comment by ocefpaf** [comment]
> Sure, but can you tell me what I need to do?

Add your GitHub handle in the list at the end of the recipe file.

**Comment by DManowitz** [comment]
@ocefpaf Done

**Pull request merged**
